# Author: Dick Mule
# Purpose: Compose file for react app and nginx container
version: '3'
volumes:
  node-modules:
services:
  # nginx
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - "80:8000"
    expose:
      - "80"
  # React frontend
  finx-io:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: finx-io
    container_name: finx-io
    command: bash -c 'yarn && yarn run'
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - PORT=3000
    volumes:
      - ./finx-io:/finx-io/finx-io
    ports:
      - "3000:3000"
    expose:
      - "3000"
